[package]
name = "bevy_pipelines_ready"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Bevy plugin for tracking render pipeline status."
repository = "https://github.com/rparrett/bevy_pipelines_ready"
homepage = "https://github.com/rparrett/bevy_pipelines_ready"
documentation = "https://docs.rs/bevy_pipelines_ready"
keywords = ["bevy", "gamedev"]
categories = ["game-development"]
readme = "README.md"
exclude = [".github"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11"
crossbeam-channel = "0.5.8"